language: cpp

os: linux
sudo: false
dist: trusty
compiler: clang

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
      - cmake
      - libboost-dev
      - libboost-test-dev
      - libboost-program-options-dev
      - lcov

script:
  - mkdir -p build && cd build
  - cmake .. -DENABLE_COVERAGE=ON
  - make
  - make test
  - make gcov

# Hook code coverage report with codecov.io
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

# Disable notifications
notifications:
  email: false

